version: '3.8'

services:
  web:
    build: .
    ports:
      - "2000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ayush123
      MYSQL_DATABASE: store
      MYSQL_USER: ayush
      MYSQL_PASSWORD: ayush123
    ports:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker_script/mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
